sudo: required

language: python

env:
  global:
    - DOCKER_TLS_VERIFY=1
    - DOCKER_CERT_PATH=.docker-machine

before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws s3 sync "s3://${AWS_BUCKET_NAME}/docker-machine" .docker-machine --include "*"
  - docker build -t deepqa:latest .
  - docker-compose up -d
